### ISSUE TITLE
trimmomatic 

### ISSUE THREAD

**Issue by alexkeeley** [sheffield-bioinformatics-core/microbial-pipeline#2]
Hi, 

I am working on sharc within an interactive node and trying to run microbial pipelines which have worked on CLIMB. The issue seems to be calling the tools from the singularity 

Trimmomatic: 

md1ake@sharc-node002 md1ake]$ singularity exec /usr/local/community/Florey/singularity/microbial-pipeline.simg trimmomatic PE -phred33 SW101A_S1_L001_R1_001.fastq.gz SW101A_S1_L001_R2_001.fastq.gz SW101A_S1_L001_R1_001.paired.fastq.gz SW101A_S1_L001_R1_001.unpaired.fastq.gz SW101A_S1_L001_R2_001.paired.fastq.gz SW101A_S1_L001_R2_001.unpaired.fastq.gz ILLUMINACLIP:/data/md1ake/Alex/adapters/TruSeq3-PE-2.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

is giving following error message: 

/.singularity.d/actions/exec: 9: exec: trimmomatic: not found

The same error occurs replacing "trimmomatic" with:
java -jar trimmomatic
java -jar trimmomatic-0.39.jar

Many thanks,

**Comment by markdunning** [comment]
Hi,

Thanks for the feedback. The location of the trimmomatic jar file is saved in the variable TRIMMOMATIC. So you should be able to do:-

```
java -jar $TRIMMOMATIC
```

In order to call it. But there is no way you would have known that! I'll find a place to document this.

Cheers,
Mark

**Comment by alexkeeley** [comment]
Many thanks for this,

Alex

**Comment by alexkeeley** [comment]
Thanks, 

/usr/local/community/Florey/singularity/microbial-pipeline.simg java -jar $TRIMMOMATIC
(or when I run the script above replacing "trimmomatic" with "java -jar $TRIMMOMATIC")

it errors 
/usr/bin/java: /usr/bin/java: cannot execute binary file

Thanks again, 

Alex

**Comment by markdunning** [comment]
Hmm, it looks like the environment variables are not being seeing by singularity

This will work for now until I find a better way

```
singularity exec /usr/local/community/Florey/singularity/microbial-pipeline.simg java -jar /opt/Trimmomatic-0.36/trimmomatic-0.36.jar
```

**Comment by alexkeeley** [comment]
Thank you,

This is working now.

Alex
